apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: geocache-ingress
  labels:
    app: geocache
spec:
  rules:
    - host: "mikro.kaart.com"
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 80
          - path: /data/(.*)
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 80
          - path: /api/v1/(.*)
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 80
  tls:
    - hosts:
        - "mikro.kaart.com"
      secretName: mikro-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: https://mikro.kaart.com/$1
  name: geocache-ingress-old
  labels:
    app: geocache
spec:
  rules:
    - host: "micro.kaart.com"
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80
  tls:
    - hosts:
        - "micro.kaart.com"
      secretName: micro-ingress-cert
