apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mikro
  labels:
    app: mikro-backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: mikro-backend
  template:
    metadata:
      labels:
        app: mikro-backend
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: mikro-backend
        image: "{{ .Values.image.repository }}/mikro-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      - {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mikro
  labels:
    app: mikro-frontend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: mikro-frontend
  template:
    metadata:
      labels:
        app: mikro-frontend
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: mikro-frontend
        image: "{{ .Values.image.repository }}/mikro-frontend:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        - {{- toYaml . | nindent 8 }}
      {{- end }}
