apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mikro
spec:
  selector:
    app: mikro-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mikro
spec:
  selector:
    app: mikro-frontend
  ports:
    - protocol: TCP
      port: 80
