apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: geocache-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geocache-database
  template:
    metadata:
      labels:
        app: geocache-database
    spec:
      containers:
        - name: geocache-database
          image: registry.gitlab.com/gokaart/docker-images/postgis
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            # Mongoose database information
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: geocache-backend-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: geocache-backend-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geocache-backend-secrets
                  key: POSTGRES_PASSWORD
      imagePullSecrets:
        - name: regcred
