apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: geocache-client
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: geocache-client
  template:
    metadata:
      labels:
        app: geocache-client
    spec:
      containers:
        - name: geocache-client
          image: registry.gitlab.com/gokaart/geocash/geocache-client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 30