apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: geocache-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geocache-server
  template:
    metadata:
      labels:
        app: geocache-server
    spec:
      containers:
        - name: geocache-server
          image: registry.gitlab.com/gokaart/mongoose/geocache-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: APP_BASE_URL
            # Mongoose database information
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: POSTGRES_ENDPOINT
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: POSTGRES_PORT
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: JWT_SECRET_KEY
            - name: SSO_API_URL
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: SSO_API_URL
            - name: JWT_COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mikro-backend-secrets
                  key: JWT_COOKIE_DOMAIN
      imagePullSecrets:
        - name: regcred
